---

- hosts: all
  vars_files:
    - vars/apt_packages.yml
    - vars/python_packages.yml
  tasks:
    - include: tasks/base_setup.yml
      tags: base
    - include: tasks/apt.yml
      tags: base,apt
    - include: tasks/python_packages.yml
      tags: base,python

- hosts: rsbteaching
  roles:
    - role: oefenweb.postfix
      tags: base,mail
      vars:
        postfix_domain: "{{inventory_hostname}}"
        postfix_notify_email: "{{admin_email}}"
        postfix_relayhost: "smtphost.anu.edu.au"
        postfix_relayhost_port: 25
        postfix_smtpd_relay_restrictions: [ permit_sasl_authenticated,permit_mynetworks,reject_unauth_destination]
    - role: fail2ban
      tags: base,security
      vars:
        fail2ban_ignoreip: >
          127.0.0.1/8
          150.203.0.0/16
          130.56.0.0/16
        fail2ban_loglevel: INFO
        fail2ban_services:
          - name: pam-generic
            enabled: true
            port: all
            filter: pam-generic
            logpath: /var/log/auth.log
            maxretry: 6
            banaction: iptables-allports
          - name: "ssh"
            enabled: "true"
            port: "ssh"
            filter: "sshd"
            logpath: "/var/log/auth.log"
            maxretry: 6
    - role: geerlingguy.certbot
      vars:
        certbot_admin_email: "{{admin_email}}"
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: [nginx]
        certbot_certs:
          - email: "{{admin_email}}"
            domains:
              - "{{inventory_hostname}}"
          - email: "{{admin_email}}"
            domains:
              - "{{jupyterhub_fqdn}}"
          - email: "{{admin_email}}"
            domains:
              - "{{rstudio_fqdn}}"
          - email: "{{admin_email}}"
            domains:
              - "{{machine_fqdn}}"
      tags: web,letsencrypt
    - role: geerlingguy.nginx
      tags: web,nginx
      vars:
        nginx_remove_default_vhost: true
        nginx_vhosts:
          - listen: "443 ssl http2"
            server_name: "{{rstudio_fqdn}}"
            server_name_redirect: "www.{{rstudio_fqdn}}"
            state: "present"
            filename: "rstudio.conf"
            extra_parameters: |
              ssl_certificate     /etc/letsencrypt/live/{{rstudio_fqdn}}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{rstudio_fqdn}}/privkey.pem;
              location / {
                   proxy_pass http://localhost:8787/;
                   proxy_redirect http://localhost:8787/ $scheme://$host/;
                   proxy_http_version 1.1;
                   proxy_set_header Upgrade $http_upgrade;
                   proxy_set_header Connection $connection_upgrade;
                   proxy_read_timeout 20d;
              }
          - listen: "443 ssl http2"
            server_name: "{{machine_fqdn}}"
            server_name_redirect: "www.{{machine_fqdn}}"
            state: "present"
            filename: "varwww.conf"
            extra_parameters: |
               root /var/www/html;
               index index.html index.htm index.nginx-debian.html;
               location / {
                      try_files $uri $uri/ =404;
                      autoindex on;
                      autoindex_exact_size off;
                      autoindex_localtime on;
                      # CORS stuff to allow access to these files from igv.org/app
                      if ($request_method = 'OPTIONS') {
                         add_header 'Access-Control-Allow-Origin' '*';
                         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                         add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                         add_header 'Access-Control-Max-Age' 1728000;
                         add_header 'Content-Type' 'text/plain; charset=utf-8';
                         add_header 'Content-Length' 0;
                         return 204;
                      }
                      if ($request_method = 'POST') {
                         add_header 'Access-Control-Allow-Origin' '*';
                         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                         add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                         add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
                      }
                      if ($request_method = 'GET') {
                         add_header 'Access-Control-Allow-Origin' '*';
                         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                         add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                         add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
                      }
               }
               ssl_certificate     /etc/letsencrypt/live/{{machine_fqdn}}/fullchain.pem;
               ssl_certificate_key /etc/letsencrypt/live/{{machine_fqdn}}/privkey.pem;
    - role: jupyterhub
      vars:
        jupyterhub_nginx: true
        jupyterhub_hostname: "{{jupyterhub_fqdn}}"
      tags: web,jupyterhub
    - role: r
      vars:
        r_cran_mirror: "https://cloud.r-project.org"
        r_install_dev: true
        r_install: # apt packages
          - r-recommended
          - libsqlite3-dev
          - libcurl4-openssl-dev
          - libssl-dev
          - pandoc
          - libxml2-dev
          - libxslt1-dev
        r_packages: # cran or bioconductor (R) packages
          - name: devtools
          - name: IRdisplay
          - name: IRkernel
          - name: tidyverse
          - name: ggplot2
        r_run: |
          IRkernel::installspec(user = FALSE)
      tags: web,r
    - role: oefenweb.rstudio_server
      rstudio_server_auth_required_user_group: users
      rstudio_server_www_port: 8787
      rstudio_server_www_address: 127.0.0.1
      rstudio_server_version: "1.2.5042"
      tags: web,rstudio


- include: dousers_TODO_$COURSE.yml
# add a line line this for each course
