- name: Set hostname
  hostname: name="{{inventory_hostname}}"

- name: Set hosts
  blockinfile:
      state: present
      dest: /etc/hosts
      block: >
        127.0.0.1 localhost
        127.0.0.1 {{inventory_hostname}}
        127.0.0.1 {{inventory_hostname_short}}

- name: Generate locales
  locale_gen:
      name: "{{item}}"
  with_items:
    - en_AU.UTF-8

- name: Passwordless Sudo
  lineinfile:
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    regexp: "^%sudo"
    state: present
    dest: /etc/sudoers
    validate: "visudo -cf %s"

- name: Password-ed SSH
  lineinfile:
    line: "PasswordAuthentication yes"
    regexp: "^PasswordAuthentication"
    state: present
    dest:  /etc/ssh/sshd_config
