# vars file for r
---
r_repository:
  - type: deb
    url: "{{ r_cran_mirror }}/bin/linux/ubuntu {{ ansible_distribution_release }}-cran35/" 
r_apt_key: E298A3A825C0D65DFD57CBB651716619E084DAB9

r_dependencies:
  - r-base
  - "{{ 'r-base-dev' if r_install_dev else '' }}"
